fix - env

diff --git a/.github/workflows/Deployment.yaml b/.github/workflows/Deployment.yaml
--- a/.github/workflows/Deployment.yaml
+++ b/.github/workflows/Deployment.yaml
@@ -9,6 +9,23 @@ env:
   PROJECT: "HecBillingCustomer"
   PROJECT_URL: "https://dev.hecbill.hecticus.com"
 
+
+steps:
+      - name: Set GCP env vars
+        run: |
+          if [[ "$GITHUB_REF_NAME" == "main" ]]; then
+            echo "GCP_PROJECT_ID=hecbilling-203521" >> $GITHUB_ENV
+            echo "GCP_VM_ZONE=us-east1-b" >> $GITHUB_ENV
+            echo "GCP_VM_NAME=customer-portal-app" >> $GITHUB_ENV
+          elif [[ "$GITHUB_REF_NAME" == "test-actions" ]]; then
+            echo "GCP_PROJECT_ID=hecbilling-203521" >> $GITHUB_ENV
+            echo "GCP_VM_ZONE=us-east1-b" >> $GITHUB_ENV
+            echo "GCP_VM_NAME=customer-portal-app" >> $GITHUB_ENV
+          else
+            echo "Error: Invalid branch name '$GITHUB_REF_NAME'. Valid branches are 'main' and 'test-actions'."
+            exit 1
+          fi
+
 jobs:
   deploy:
     runs-on: ubuntu-latest
@@ -67,21 +84,21 @@ jobs:
       with:
         credentials_json: ${{ secrets.GCP_SA_KEY }}
 
-    - name: "Build and Deploy"
-      run: |
-        if [[ $GITHUB_REF_NAME == 'main' ]]; then
-          GCP_PROJECT_ID=hecbilling-203521
-          GCP_VM_ZONE=us-east1-b
-          GCP_VM_NAME=customer-portal-app   
-        elif [[ $GITHUB_REF_NAME == 'test-actions' ]]; then
-          GCP_PROJECT_ID=hecbilling-203521
-          GCP_VM_ZONE=us-east1-b
-          GCP_VM_NAME=customer-portal-app   
-        else
-            echo "Error: Invalid branch name '$GITHUB_REF_NAME'. Valid branches are 'main' and 'test-actions'."
-            exit 1
-        fi
-
+          #    - name: "Build and Deploy"
+          #      run: |
+          #        if [[ $GITHUB_REF_NAME == 'main' ]]; then
+          #          GCP_PROJECT_ID=hecbilling-203521
+          #          GCP_VM_ZONE=us-east1-b
+          #          GCP_VM_NAME=customer-portal-app   
+          #        elif [[ $GITHUB_REF_NAME == 'test-actions' ]]; then
+          #          GCP_PROJECT_ID=hecbilling-203521
+          #          GCP_VM_ZONE=us-east1-b
+          #          GCP_VM_NAME=customer-portal-app   
+          #        else
+          #            echo "Error: Invalid branch name '$GITHUB_REF_NAME'. Valid branches are 'main' and 'test-actions'."
+          #            exit 1
+          #        fi
+          #
     - name: Deploy to GCP VM
       run: |
         gcloud compute ssh ${{ secrets.GCP_VM_NAME }} \
